---
title: "Class 11: AlphaFold"
author: "Dalena (PID: A17327787)"
format: html
toc: TRUE
---

Here we read the results from AlphaFold and try to interpret all the models and quality score metrics:

```{r}
library(bio3d)

pth <- "dimer_23119/"
pdb.files <- list.files(path=pth,full.names=TRUE,pattern=".pdb")
```

Align and superpose all these models

```{r}
file.exists(pdb.files)
```

```{r}
pdbs <- pdbaln(pdb.files, fit = TRUE, exefile="msa")
```

```{r}
library(bio3dview)

view.pdbs(pdbs)
```

```{r}
plot(pdbs$b[1,],type="l",ylim=c(0,100),ylab="pLDDT score")
lines(pdbs$b[2,],type="l", col="dodgerblue1")
lines(pdbs$b[3,],type="l", col="orange")
lines(pdbs$b[4,],type="l", col="seagreen")
lines(pdbs$b[5,],type="l", col="maroon")

```

```{r}
core <-core.find(pdbs)
```

```{r}
core.inds <-print(core,vol=0.5)
xyz <- pdbfit(pdbs,core.inds,outpath="corefit_structures")
```

## RMSF 

```{r}
rf <- rmsf(xyz)

plotb3(rf, sse=pdbs)
abline(v=100, col="gray", ylab="RMSF")
```

## Heat Maps

```{r}
rd <- rmsd(pdbs, fit=T)
range(rd)
```

```{r}
library(pheatmap)

colnames(rd) <- paste0("m",1:5)
rownames(rd) <- paste0("m",1:5)
pheatmap(rd)
```

## Reading PAE JSON files

```{r}
library(jsonlite)

# Listing of all PAE JSON files
pae_files <- list.files(path=pth,
                        pattern=".*model.*\\.json",
                        full.names = TRUE)
```

```{r}
pae1 <- read_json(pae_files[1],simplifyVector = TRUE)
pae5 <- read_json(pae_files[5],simplifyVector = TRUE)

attributes(pae1)
```

```{r}
head(pae1$plddt) 
```

```{r}
pae1$max_pae
pae5$max_pae
```

```{r}
plot.dmat(pae5$pae, 
          xlab="Residue Position (i)",
          ylab="Residue Position (j)",
          grid.col = "black",
          zlim=c(0,30))

plot.dmat(pae1$pae, 
          xlab="Residue Position (i)",
          ylab="Residue Position (j)",
          grid.col = "black",
          zlim=c(0,30))
```

## Score Residue Conservation from alignment file

```{r}
aln_file <- list.files(path=pth,
                       pattern=".a3m$",
                        full.names = TRUE)
aln_file
```

```{r}
aln <- read.fasta(aln_file[1], to.upper = TRUE)
```

```{r}
dim(aln$ali)
```

```{r}
sim <- conserv(aln)
```

```{r}
plotb3(sim[1:99], sse=trim.pdbs(pdbs, chain="A"),
       ylab="Conservation Score")
```

```{r}
con <- consensus(aln, cutoff = 0.9)
con$seq
```

```{r}
m1.pdb <- read.pdb(pdb.files[1])
occ <- vec2resno(c(sim[1:99], sim[1:99]), m1.pdb$atom$resno)
write.pdb(m1.pdb, o=occ, file="m1_conserv.pdb")
```

